# Generated by Django 2.2.3 on 2019-07-04 10:38

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveGoogleSearch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('query', models.CharField(max_length=100)),
                ('status', models.BooleanField(default=True)),
                ('date_added', models.DateTimeField(default=datetime.datetime(2019, 7, 4, 10, 38, 33, 711720, tzinfo=utc))),
                ('chat_id', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ActiveInstagramSearch',
            fields=[
                ('activegooglesearch_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='telega.ActiveGoogleSearch')),
            ],
            bases=('telega.activegooglesearch',),
        ),
        migrations.CreateModel(
            name='GoogleUrl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=1000)),
                ('status', models.BooleanField(default=True)),
                ('requested', models.DateTimeField(blank=True, null=True)),
                ('active', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='telega.ActiveGoogleSearch')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InstagramUrl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=1000)),
                ('status', models.BooleanField(default=True)),
                ('requested', models.DateTimeField(blank=True, null=True)),
                ('active', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='telega.ActiveInstagramSearch')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
